name: Build Linux Kernel Module

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    

    - name: Set up kernel build essentials
      run: |
        sudo apt-get update
        sudo apt-get install -y \
              build-essential \
              kmod \
              linux-headers-$(uname -r)

    - name: Build kernel module
      run: |
        cd lkm
        make
